


void main(){
  try {
    int result = 10 ~/ 10;
    print(result);
  } catch (e) {
    print('An error occured: $e');
  }
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               